In [2]:
1.#import numpy as np and print  the version number
import numpy as np
print(np. __version__)

1.13.3


In [3]:
2.# How to  create a  1D Array?
import numpy as np
df=np.arange(10)
df

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
3.# How  to  create a boolean Array?
import  numpy  as  np
df=np.ones((3,3),dtype=bool)
df

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [5]:
4#How to reshape an array?
import  numpy as  np
df=np.arange(10)
df=df.reshape(2,-1)
df

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
5#How to extract items that satisfy a given condition from 1D array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
df=arr[arr % 2 == 1]
df

array([1, 3, 5, 7, 9])

In [4]:
6#How to get the common items between two python numpy arrays?
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6,5,7,8,4,5])
b = np.array([7,2,10,2,7,4,9,4,9,8,5,7,5,1,2])
np.intersect1d(a,b)


array([1, 2, 4, 5, 7, 8])

In [ ]:
7.How to remove from one array those items that exist in another?